# Generated by Django 4.2.16 on 2024-10-13 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_landmark_history_landmark_image_landmark_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landmark',
            name='price',
        ),
        migrations.AddField(
            model_name='landmark',
            name='price_max',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landmark',
            name='price_min',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('rating', models.FloatField()),
                ('cuisine_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='restaurants/')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='core.city')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('rating', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('price_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amenities', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='hotels/')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='core.city')),
            ],
        ),
    ]
